# Second content layer: "Free" titles, deeper long-form copy, extra landing pages and more blog posts.
# Loaded by build.py after content.py (it updates PAGES / USE_CASES / POSTS in place).
# "Free" is truthful here: designing, previewing and saving drafts costs nothing; you pay once only to publish.

FREE_NOTE = "Free to design and preview. Pay once only when you publish."

TITLES = {
    "home": ("Design Free Digital Invitations with QR Code | MyInviteQR",
             "Design free digital invitations with a QR code in minutes. Pick a template, share one link and track RSVPs online. Free to design, pay once only to publish.",
             "Design Free Digital Invitations with QR Code"),
    "how": ("Free Digital Invitation Maker: How It Works | MyInviteQR",
            "See how to make a free digital invitation with a QR code in four steps: create your event, pick a template, customize it and share it. Free to design.",
            None),
    "pricing": ("Pricing: Design Free, Publish from $9.99 | MyInviteQR",
                "Design digital invitations free and pay once only to publish. Essential $9.99, Premium $19.99, no subscription. QR code and online RSVP included.",
                None),
    "templates": ("50 Free Digital Invitation Templates to Edit | MyInviteQR",
                  "Browse 50 free digital invitation templates for weddings, birthdays, baby showers, quinceañeras and corporate events. Edit online and share with a QR code.",
                  None),
    "faq": ("FAQ: Free Digital Invitations and QR Codes | MyInviteQR",
            "Answers about free digital invitations, QR codes, online RSVP, guest limits and pricing. Learn what is free, what you pay for and how sharing works.",
            None),
    "blog": ("Free Invitation Ideas, Wording and Guides | MyInviteQR Blog",
             "Free invitation wording ideas, etiquette tips and step-by-step guides for weddings, birthdays, baby showers and more from the MyInviteQR blog.",
             None),
    "wedding": ("Free Digital Wedding Invitations with QR Code | MyInviteQR",
                "Design free digital wedding invitations with a QR code and online RSVP. Share one link with every guest and track replies in real time. Pay only to publish.",
                "Free digital wedding invitations your guests will love"),
    "birthday": ("Free Digital Birthday Invitations Online | MyInviteQR",
                 "Design free digital birthday invitations with a QR code in minutes. Kids and adult templates, online RSVP and one link to text or email. Pay only to publish.",
                 "Free digital birthday invitations that get the party started"),
    "baby": ("Free Digital Baby Shower Invitations | MyInviteQR",
             "Design free digital baby shower invitations with a QR code and online RSVP. Soft templates, easy replies and no paper. Free to design, pay once to publish.",
             "Free digital baby shower invitations, sweet and simple"),
    "quince": ("Free Digital Quinceañera Invitations | MyInviteQR",
               "Design free digital quinceañera invitations with a QR code and online RSVP for up to 1,000 guests. English and Spanish templates. Pay only to publish.",
               "Free digital quinceañera invitations for a celebration to remember"),
    "corporate": ("Free Corporate Event Invitations Online | MyInviteQR",
                  "Design free corporate event invitations with online RSVP and a QR code. Professional templates for galas, launches and team events. Pay only to publish.",
                  "Free corporate event invitations that look professional"),
    "qr": ("Free QR Code Invitations: Create and Share | MyInviteQR",
           "Design free QR code invitations guests scan to open your event and RSVP. Add the code to cards, signs and screens. Free to design, pay once to publish.",
           "Free QR code invitations guests scan to open and RSVP"),
    "rsvp": ("Free Online RSVP for Events: Track Guests | MyInviteQR",
             "Collect RSVPs online with one link or QR code. See who is coming and who opened your invitation. Free to design, pay once to publish. No app for guests.",
             "Free online RSVP that makes tracking guests effortless"),
}

EXTRA_KEYWORDS = {
    "home": "free digital invitations, free online invitations, free invitation maker, free e-invitations, free QR code invitations, free RSVP invitations, digital invitations with QR code, online invitation maker USA, invitation templates free",
    "wedding": "free digital wedding invitations, free online wedding invitations, free wedding invitation maker, free e-invite wedding, digital wedding invitation with RSVP, wedding invitation QR code, wedding website invitation",
    "birthday": "free digital birthday invitations, free online birthday invitations, free birthday invitation maker, kids birthday e-invite free, birthday invitation text message, birthday invitation with RSVP",
    "baby": "free digital baby shower invitations, free online baby shower invitations, free baby shower e-invite, baby shower invitation maker, gender reveal invitation free, baby shower RSVP",
    "quince": "free digital quinceañera invitations, free quince invitations online, quinceañera invitation maker, sweet 16 invitations free, invitaciones de quince años digitales gratis",
    "corporate": "free corporate event invitations, free business event invitation maker, company party invitation free, gala invitation online, conference invitation with RSVP",
    "qr": "free QR code invitations, free QR code invitation maker, QR code wedding invitation free, QR invitation card, scan to RSVP QR code, QR code birthday invitation",
    "rsvp": "free online RSVP, free RSVP tracker, free RSVP website, RSVP link for events, online guest list manager, collect RSVPs online free",
}

# ----------------------------------------------------------------------------- long-form additions for the seven original pages
EXTRAS = {
    "wedding": dict(
        what_title="What are digital wedding invitations?",
        what=["Digital wedding invitations are online invitations you send by link, text or email instead of by mail. Guests open a page on their phone with your names, the ceremony and reception details, a map and an RSVP button. With MyInviteQR every invitation also gets its own QR code, so you can put the same invitation on a printed save-the-date, a program or a welcome sign.",
              "Couples in the United States choose digital invitations because they are faster to send, cheaper than printing and postage, and far easier to keep accurate. If the venue, the time or the dress code changes, you edit the invitation once and every guest sees the update. Replies arrive in one guest list, so you always know your headcount for the caterer."],
        tips_title="Tips for sending digital wedding invitations",
        tips=["Send save-the-dates 6 to 9 months out and the full invitation 6 to 8 weeks before the wedding.", "Add a reply-by date so you have a final headcount at least three weeks before the day.",
              "Put your QR code on the printed save-the-date so older guests can scan instead of typing a link.", "Use groups (family, friends, wedding party) to keep the guest list organized.", "Send a personal link to each guest with Premium so you can see who has opened it."],
        faqs=[("Can I add a wedding website link or registry?", "Yes. Add text or a link anywhere on your invitation with the editor, for example your registry or accommodation details."),
              ("Can guests RSVP for a plus one or their family?", "Yes. Guests choose yes, no or maybe and enter the number of people in their party."),
              ("Can I print my digital wedding invitation?", "You can download the QR code and add it to printed cards. Many couples send a printed card to close family and the digital invitation to everyone else.")]),
    "birthday": dict(
        what_title="What is a digital birthday invitation?",
        what=["A digital birthday invitation is an online invitation you send by text, email or messaging app. Instead of handing out paper cards, you share one link that opens a colorful page with the date, time, address and an RSVP button. Every MyInviteQR invitation also comes with a QR code you can print for signs or party bags.",
              "Parents like digital invitations because they can be finished in minutes, even the night before a party. You can change the address or the start time later and everyone sees the update, and you get an accurate headcount for cake, food and favors without chasing anyone in group chats."],
        tips_title="Tips for a birthday invitation people answer",
        tips=["Include the start and end time so parents know when to pick up.", "Add the address and parking notes directly in the invitation.", "Ask for a reply at least a week before the party.",
              "Mention allergies or themes (costumes, swimwear) in the details.", "Share the link in the class or family group chat so everyone gets it at once."],
        faqs=[("Can I send the invitation by text message or WhatsApp?", "Yes. Copy your invitation link and paste it into any text or chat app. Guests tap the link to open the invitation."),
              ("Can I use it for adult birthdays and milestone parties?", "Yes. Choose an elegant or modern template for 30th, 40th, 50th and other milestone birthdays.")]),
    "baby": dict(
        what_title="What is a digital baby shower invitation?",
        what=["A digital baby shower invitation is an online invitation with the date, place and details of the shower, sent as a link or QR code. Guests open it on their phone and reply in seconds, so you do not have to collect answers by text or mail.",
              "Because it is online, you can add a registry note, parking information or a co-host contact, and update it whenever plans change. It also works for gender reveals, sip-and-see events and couples showers."],
        tips_title="Tips for baby shower invitations",
        tips=["Send invitations 4 to 6 weeks before the shower.", "Mention where the registry is, or add a gift note on the invitation.", "Set the reply-by date about a week before so you can plan food.",
              "Choose soft neutral colors if you are keeping the gender a surprise.", "Share the link with the host committee so everyone invites from the same source."],
        faqs=[("Can I ask guests to bring a book or a diaper pack?", "Yes. Add a short line in the details of your invitation, for example: instead of a card, bring a favorite children's book."),
              ("Can I make a co-ed baby shower invitation?", "Yes. Choose any template and edit the text. Many hosts use modern or botanical designs for couples showers.")]),
    "quince": dict(
        what_title="What is a digital quinceañera invitation?",
        what=["A digital quinceañera invitation is an online invitation for a fifteenth birthday celebration, shared as a link or QR code. It can include the Mass, the reception, the schedule, the dress code and an RSVP button, in English, Spanish or both.",
              "Quinceañeras often have hundreds of guests and many moving parts, so a single page that families can open on their phones makes a big difference. Edit details after sending, group guests by family and track every reply in one list."],
        tips_title="Tips for quinceañera invitations",
        tips=["Include both the ceremony and the reception with times and addresses.", "Write the invitation in the language your family reads most, or add both.", "Use groups for family, friends and the court of honor.",
              "Ask for a reply at least a month ahead for a large celebration.", "Add a QR code to programs and welcome signs."],
        faqs=[("Can I include the church ceremony and the party?", "Yes. Add both events to the same invitation with their own times and addresses."),
              ("Can I invite more than 300 guests?", "Yes. Premium supports up to 1,000 guests.")]),
    "corporate": dict(
        what_title="What are digital corporate event invitations?",
        what=["Digital corporate event invitations are online invitations for launches, galas, conferences, client dinners and company parties. Invitees open a branded page with the agenda, venue and an RSVP button, and you see replies in real time.",
              "They are faster to send than printed invitations, easy to update when the agenda changes, and simple to track. With Premium you can remove MyInviteQR branding and use a custom link."],
        tips_title="Tips for corporate event invitations",
        tips=["Lead with the value: who is speaking and what guests will gain.", "Put date, time and venue at the top and the RSVP button right below.", "Add dress code and parking or transit notes.",
              "Set a firm reply-by date so catering numbers are accurate.", "Use groups to separate VIPs, clients and staff."],
        faqs=[("Can I use my company colors?", "Yes. Choose from more than 130 color palettes or pick your own colors in the editor."),
              ("Can I send different links to different guests?", "Yes. Premium includes individual links for each guest.")]),
    "qr": dict(
        what_title="What is a QR code invitation?",
        what=["A QR code invitation is an invitation that includes a scannable code. When a guest points their phone camera at the code, their browser opens your digital invitation with the event details and an RSVP button. No app and no typing are required.",
              "The QR code is especially useful where you cannot click a link: a printed save-the-date, a welcome sign, a menu, a poster or a screen at the venue. MyInviteQR creates the code for you and keeps it working while your event is active."],
        tips_title="Tips for using QR codes on invitations",
        tips=["Print the code at least 0.8 inches wide with a clear margin around it.", "Use dark code on a light background for the best scanning.", "Add a short instruction such as Scan to RSVP.",
              "Test the code with both an iPhone and an Android phone before you print.", "Keep the code away from busy patterns and folds."],
        faqs=[("What size should a QR code be on an invitation?", "At least 0.8 inches (2 cm) wide for close scanning, and larger for signs and posters."),
              ("Do guests need a QR scanner app?", "No. Modern iPhone and Android cameras scan QR codes automatically.")]),
    "rsvp": dict(
        what_title="What is an online RSVP?",
        what=["An online RSVP lets guests answer an invitation from a web page instead of by phone, text or mail. On MyInviteQR guests tap the RSVP button, choose yes, no or maybe, enter how many people are coming and can leave a message.",
              "For hosts, it replaces scattered replies with a live guest list. Filter by confirmed, pending, declined, maybe, opened or not opened, and export the list to CSV for your caterer or venue."],
        tips_title="Tips for getting more RSVPs",
        tips=["Put the RSVP button at the top of your invitation, not only at the bottom.", "Set a clear reply-by date.", "Send a friendly reminder to guests who opened the invitation but have not replied.",
              "Ask for party size so you know the true headcount.", "Use individual links so each guest is recognized automatically (Premium)."],
        faqs=[("Can guests change their answer?", "Guests can open the invitation again and update their response."),
              ("Can I see who has not replied?", "Yes. Use the Pending and Not opened filters in your guest list.")]),
}

# ----------------------------------------------------------------------------- new landing pages (same fields as USE_CASES + extras)
NEW_PAGES = {
    "graduation": dict(
        file="graduation-invitations.html", crumb="Graduation invitations",
        title="Free Digital Graduation Invitations | MyInviteQR",
        desc="Design free digital graduation invitations with a QR code and online RSVP. High school, college and grad party templates. Free to design, pay once to publish.",
        keywords="free digital graduation invitations, graduation party invitations online, graduation announcement digital, high school graduation invitation, college graduation invitation, graduation open house invitation, graduation invitation with RSVP",
        name="Graduation", h1="Free digital graduation invitations to celebrate the big day",
        lead="Invite family and friends to your graduation ceremony or party with a modern online invitation. Share one link, collect RSVPs and update the details any time.",
        why_title="Why digital graduation invitations work", why_sub="Perfect for busy families and last-minute plans.",
        why=[("zap", "Ready before the ceremony", "Graduations sneak up fast. Finish your invitation in minutes and share it the same day."),
             ("users", "Easy for relatives everywhere", "Grandparents and out-of-town guests open one link on their phone and reply in seconds."),
             ("edit", "Update the details", "Cap-and-gown time changed? Party moved indoors? Edit once and everyone sees it.")],
        steps_title="Create a graduation invitation in four steps",
        tpl_title="Graduation invitation templates", tpl_sub="Bold posters, photo grids and clean modern layouts.", templates=["Photo Grid Party", "Poster Bold", "Modern Hero", "Grid & Gold"],
        wording_title="Graduation invitation wording ideas", wording_intro="Short, proud and easy to adapt.",
        wording=["Please join us as we celebrate Alex's graduation from Lincoln High School. Saturday, May 30 at 2:00 PM.", "She did it! Come celebrate Maya's graduation with food, music and family.", "The tassel was worth the hassle. Join us for a graduation party."],
        split_title="Graduation party details in one place", split_text="Share the ceremony time, the party address and a photo of the graduate. Guests reply with their party size and you plan food and seating with confidence.",
        split_checks=["Add your graduation photos", "School colors with 130+ palettes", "Online RSVP with party size", "Share by text or QR code"], split_alt="Digital graduation party invitation on a phone",
        what_title="What is a digital graduation invitation?",
        what=["A digital graduation invitation is an online invitation for a graduation ceremony, open house or party. Guests open a link or scan a QR code to see the time, place and details and to RSVP.",
              "It is the modern replacement for mailed announcements: quicker to send, easy to update and simple to track. You can still print the QR code on a card for relatives who prefer paper."],
        tips_title="Tips for graduation invitations", tips=["Send invitations 4 to 6 weeks before the ceremony.", "Include ticket limits or seating notes for the ceremony.", "Add a photo of the graduate.", "State the party start time clearly, especially for open houses.", "Ask for a reply by a set date so you can order food."],
        faqs=[("When should I send graduation invitations?", "Most families send them 4 to 6 weeks before the ceremony or party."),
              ("Can I use it for a graduation open house?", "Yes. Add the open-house hours in the details so guests know they can stop by any time."),
              ("Can I make one for college or high school?", "Yes. Every template is fully editable, so it works for any graduation."),
              ("Do guests need an account?", "No. Guests open the link and reply without creating an account.")],
        cta_title="Celebrate the graduate", cta_text="Create a graduation invitation and share it today."),
    "anniversary": dict(
        file="anniversary-invitations.html", crumb="Anniversary invitations",
        title="Free Digital Anniversary Invitations | MyInviteQR",
        desc="Design free digital anniversary invitations with a QR code and online RSVP for milestone parties. Elegant templates. Free to design, pay once to publish.",
        keywords="free digital anniversary invitations, 25th anniversary invitation online, 50th anniversary invitation digital, wedding anniversary party invitation, anniversary invitation with RSVP, anniversary e-invite",
        name="Anniversary", h1="Free digital anniversary invitations for milestone celebrations",
        lead="From a first anniversary dinner to a 50th anniversary party, create an elegant online invitation, collect RSVPs and share it with a link or QR code.",
        why_title="Why choose a digital anniversary invitation", why_sub="Elegant, personal and simple to manage.",
        why=[("heart", "Tell your story", "Add photos from your years together and a warm message in your own words."),
             ("users", "Family across the country", "Everyone opens the same link and replies from their phone."),
             ("clock", "Fast to finish", "Choose a template, add the details and share it in minutes.")],
        steps_title="Create an anniversary invitation in four steps",
        tpl_title="Anniversary invitation templates", tpl_sub="Romantic, timeless and modern designs.", templates=["Garden Romance", "Ivory Frame", "Cherry Blossom", "Emerald Night"],
        wording_title="Anniversary invitation wording ideas", wording_intro="Warm words for a special milestone.",
        wording=["Join us as we celebrate 25 years of love. Saturday, June 7 at 6:00 PM.", "Fifty years and still going strong! Celebrate Rose and Michael's golden anniversary with us.", "Help us toast to another year together."],
        split_title="Photos and memories in one invitation", split_text="Add a favorite photo, choose gold or silver accents for milestone years and share the invitation with the whole family.",
        split_checks=["Add photos from your years together", "Gold, silver and classic palettes", "Online RSVP", "Update details after sending"], split_alt="Elegant digital anniversary invitation",
        what_title="What is a digital anniversary invitation?",
        what=["A digital anniversary invitation is an online invitation for an anniversary dinner or party. It opens as a web page from a link or QR code and includes the celebration details and an RSVP button.",
              "It is a thoughtful, easy way to gather family and friends, especially when guests live in different cities."],
        tips_title="Tips for anniversary invitations", tips=["Mention the milestone in the title, for example 25 Years Together.", "Ask children or friends to host a surprise and share the private link.", "Include a dress code if it is a formal dinner.", "Add a photo collage using a photo template.", "Set a reply-by date two weeks ahead."],
        faqs=[("Can I plan a surprise anniversary party?", "Yes. Keep the invitation link private and share it only with guests."),
              ("Can I use it for a vow renewal?", "Yes. Edit the text of any template for a vow renewal or anniversary celebration."),
              ("How many guests can I invite?", "Essential supports up to 50 guests and Premium up to 1,000."),
              ("Can guests send a message?", "Guests can add a message when they RSVP.")],
        cta_title="Celebrate your anniversary", cta_text="Create an anniversary invitation your guests will treasure."),
    "gender": dict(
        file="gender-reveal-invitations.html", crumb="Gender reveal invitations",
        title="Free Digital Gender Reveal Invitations | MyInviteQR",
        desc="Design free digital gender reveal invitations with a QR code and online RSVP. Playful templates to share by link. Free to design, pay once to publish.",
        keywords="free digital gender reveal invitations, gender reveal party invitation online, gender reveal invitation template, gender reveal e-invite, gender reveal RSVP, boy or girl party invitation",
        name="Gender reveal", h1="Free digital gender reveal invitations for the big surprise",
        lead="Invite your family and friends to find out together. Create a playful online invitation in minutes and collect RSVPs in one place.",
        why_title="Why digital invitations suit gender reveals", why_sub="Fun, quick and easy to share.",
        why=[("sparkles", "Playful designs", "Stars, balloons and bold colors that match your theme."), ("send", "Share in seconds", "Send one link to the group chat and everyone has the details."), ("users", "Know who is coming", "See replies and party sizes so you can plan food and seating.")],
        steps_title="Create a gender reveal invitation in four steps",
        tpl_title="Gender reveal invitation templates", tpl_sub="Neutral, playful and magical designs.", templates=["Starry Night", "Little Star", "Balloon Bash", "Twin Moons"],
        wording_title="Gender reveal invitation wording ideas", wording_intro="Fun lines for the big question.",
        wording=["He or she? Join us to find out! Saturday at 3:00 PM.", "Boy or girl? We can't wait to celebrate with you.", "Oh baby! Come help us reveal the big news."],
        split_title="Keep the surprise, share the details", split_text="Use neutral colors on the invitation and share the link only with guests. Update details any time without reprinting.",
        split_checks=["Neutral color palettes", "Balloons, stars and confetti decorations", "Online RSVP", "QR code for signs at the party"], split_alt="Gender reveal digital invitation with balloons",
        what_title="What is a gender reveal invitation?",
        what=["A gender reveal invitation invites guests to a party where the baby's gender is revealed. A digital version is sent as a link or QR code and shows the date, place and RSVP button.",
              "It is quick to make and easy to share, and you can change the details as plans evolve."],
        tips_title="Tips for gender reveal invitations", tips=["Use neutral colors so nothing is given away.", "Add a reply-by date so you can plan the reveal moment.", "Include outdoor or weather notes if it is outside.", "Ask guests to vote or guess at the party.", "Put a QR code on a welcome sign."],
        faqs=[("Can I use blue and pink on the invitation?", "Yes. Choose any palette. Many hosts use neutral colors to keep the surprise."),
              ("Can I send it by text message?", "Yes. Copy the link and paste it into any text or chat."),
              ("Is it good for a small party?", "Yes. Essential supports up to 50 guests."),
              ("Can I edit it later?", "Yes. Change any detail and guests see the latest version.")],
        cta_title="Plan the big reveal", cta_text="Create your invitation and start collecting RSVPs."),
    "holiday": dict(
        file="holiday-party-invitations.html", crumb="Holiday party invitations",
        title="Free Digital Holiday Party Invitations | MyInviteQR",
        desc="Design free digital holiday party invitations with a QR code and online RSVP. Festive templates for family and office parties. Pay once to publish.",
        keywords="free digital holiday party invitations, christmas party invitation online, office holiday party invitation, new year's eve party invitation, year end party invitation, holiday invitation with RSVP, friendsgiving invitation",
        name="Holiday party", h1="Free digital holiday party invitations that spark the season",
        lead="From office parties to family Christmas dinners and New Year's Eve, create a festive online invitation and see who is coming.",
        why_title="Why digital holiday invitations", why_sub="The season is busy. Make inviting easy.",
        why=[("gift", "Festive designs", "Gold, red, green and midnight palettes for every kind of holiday."), ("send", "Send it fast", "Share one link with the whole team, family or friend group."), ("bell", "Get answers early", "Holiday calendars fill up. Ask for replies early and track them live.")],
        steps_title="Create a holiday party invitation in four steps",
        tpl_title="Holiday party invitation templates", tpl_sub="Confetti, poster and starry-night designs.", templates=["Confetti Night", "Year in Review", "Moonlight Dinner", "Poster Noir"],
        wording_title="Holiday party invitation wording ideas", wording_intro="Cheerful lines to get you started.",
        wording=["Join us for holiday cheer, good food and great company. Friday, December 12 at 7:00 PM.", "Ring in the new year with us! Dress to sparkle.", "The team is celebrating a great year. Please RSVP to our holiday party."],
        split_title="Office parties and family gatherings", split_text="Use groups to separate departments or family branches, and export the list for the venue or caterer.",
        split_checks=["Festive palettes and confetti", "Groups for teams and families", "Export guests to CSV", "Share by link or QR code"], split_alt="Holiday party digital invitation with confetti",
        what_title="What is a digital holiday party invitation?",
        what=["A digital holiday party invitation is an online invitation for a Christmas, Hanukkah, New Year's Eve or office party. Guests open a link or scan a QR code to see the details and RSVP.",
              "It is ideal for busy seasons because you can finish it in minutes and get replies early."],
        tips_title="Tips for holiday party invitations", tips=["Send invitations 3 to 4 weeks ahead because December calendars fill up.", "State the dress code (ugly sweater, black tie, cozy).", "Mention whether guests can bring a plus one.", "Include parking and transit details.", "Send a reminder a few days before."],
        faqs=[("When should I send holiday party invitations?", "Three to four weeks ahead works well for family parties and four to six weeks for office events."),
              ("Can I use it for New Year's Eve?", "Yes. Choose a festive or midnight-themed template."),
              ("Can I invite my whole company?", "Premium supports up to 1,000 guests."),
              ("Can I change the details later?", "Yes. Update anything and everyone sees the latest version.")],
        cta_title="Start your holiday invitation", cta_text="Pick a festive design and share it in minutes."),
    "maker": dict(
        file="free-invitation-maker.html", crumb="Free invitation maker",
        title="Free Invitation Maker Online with QR Code | MyInviteQR",
        desc="Use our free online invitation maker to design a digital invitation with photos, colors and a QR code. Free to design, pay once only to publish and share.",
        keywords="free invitation maker, online invitation maker, invitation maker with QR code, free invitation maker online, digital invitation maker, e-invite maker free, party invitation maker, custom invitation maker",
        name="Invitation maker", h1="Free online invitation maker with QR code",
        lead="Design a digital invitation from scratch or start from one of 50 templates. Drag, resize and rotate anything, upload photos and add your RSVP button and QR code.",
        why_title="Why use the MyInviteQR invitation maker", why_sub="More control than a simple template, still easy for beginners.",
        why=[("edit", "Free-form editor", "Move any text, photo, shape or decoration exactly where you want it."), ("palette", "130+ color palettes", "Change one palette and the whole design recolors itself."), ("image", "Your photos", "Upload photos, crop them to a shape and add collages.")],
        steps_title="Make your invitation in four steps",
        tpl_title="Start from a template", tpl_sub="Or start blank and design your own.", templates=["Garden Romance", "Balloon Bash", "Bento Bloom", "Poster Bold"],
        wording_title="What to include on your invitation", wording_intro="A checklist so nothing is missing.",
        wording=["Who: the host and the guest of honor.", "What: the type of event and any theme or dress code.", "When and where: the date, start time, address and parking.", "How to reply: the RSVP button and a reply-by date."],
        split_title="Design free, publish when you are ready", split_text="Building your invitation costs nothing. Save drafts, preview on a phone and come back any time. You pay once only when you publish to share it with guests.",
        split_checks=["Unlimited drafts", "Undo and redo", "Phone and full-screen preview", "Autosave"], split_alt="Free online invitation maker editor",
        what_title="What is an online invitation maker?",
        what=["An online invitation maker is a web tool for designing invitations without design software. You choose a template, change the text, colors and photos, and export or share the finished invitation.",
              "MyInviteQR goes further than a static image: your invitation is a live web page with an RSVP button, a QR code and guest tracking, so it works as your whole invitation and guest-list tool."],
        tips_title="Tips for designing a great invitation", tips=["Keep the most important details, date and place, large and near the top.", "Limit yourself to two or three fonts.", "Use high-resolution photos.", "Make sure text has strong contrast with the background.", "Preview on a phone before you publish."],
        faqs=[("Is the invitation maker really free?", "Yes. Designing, previewing and saving drafts are free. You pay once only when you publish the invitation to share it with guests."),
              ("Do I need design skills?", "No. Start from a template and change the details. The editor is drag and drop."),
              ("Can I upload my own photos?", "Yes. Upload JPG, PNG, WebP or GIF files up to 5 MB each."),
              ("Can I use it on my phone?", "Guests can view invitations on any phone. Designing works best on a computer or tablet.")],
        cta_title="Start designing", cta_text="Open the editor and make your first invitation for free."),
    "savedate": dict(
        file="save-the-date-invitations.html", crumb="Save the date",
        title="Free Digital Save the Date Invitations | MyInviteQR",
        desc="Design free digital save the dates with a QR code and online RSVP. Send one link now, add details later and update everything without reprinting.",
        keywords="free digital save the date, online save the date, save the date with QR code, digital save the date for wedding, save the date invitation maker, e-save the date, save the date text message",
        name="Save the date", h1="Free digital save the dates you can update anytime",
        lead="Announce your date now and add the details later. One link and one QR code stay the same while you fill in the venue, schedule and RSVP.",
        why_title="Why send a digital save the date", why_sub="Early, flexible and easy to follow up.",
        why=[("calendar", "Send it early", "Let guests block the date months ahead with a beautiful announcement."), ("edit", "Add details later", "Start with the date and place, then add the schedule and RSVP as plans firm up."), ("qr", "Print the QR code", "Add the code to a paper save-the-date so guests reach the same page.")],
        steps_title="Create a save the date in four steps",
        tpl_title="Save the date templates", tpl_sub="Minimal, romantic and modern layouts.", templates=["Quiet Edit", "Sand Minimal", "Twin Moons", "Magazine"],
        wording_title="Save the date wording ideas", wording_intro="Short and sweet works best.",
        wording=["Save the date. Emma and Jack are getting married on June 14, 2026. Invitation to follow.", "Mark your calendar! Sofia turns 30 on October 19.", "Save the date for the Northwind Annual Summit, March 12."],
        split_title="One link from save the date to invitation", split_text="Keep the same link and QR code from the first announcement to the final invitation. Guests always see the newest details.",
        split_checks=["Same link the whole time", "Add RSVP when you are ready", "Works for weddings and every event", "Print the QR code on cards"], split_alt="Digital save the date on a smartphone",
        what_title="What is a digital save the date?",
        what=["A digital save the date is an early online announcement of an event's date and location, shared by link, text or QR code. It lets guests plan travel and time off before the full invitation arrives.",
              "With MyInviteQR you do not need to send two separate things: publish once and update the same invitation as details are confirmed."],
        tips_title="Tips for save the dates", tips=["Send wedding save the dates 6 to 9 months ahead, and destination weddings 9 to 12 months ahead.", "Include the city and date at minimum.", "Mention that the formal invitation will follow.", "Add your wedding website if you have one.", "Include the QR code on printed cards."],
        faqs=[("When should I send a save the date?", "For weddings, 6 to 9 months ahead is common. For other events, 4 to 8 weeks."),
              ("Do I need a separate invitation later?", "No. You can update the same invitation, or design a new one if you prefer."),
              ("Can I print it?", "Yes. Download the QR code and add it to a printed card."),
              ("Does it work for birthdays?", "Yes. Use it for any event.")],
        cta_title="Save the date, beautifully", cta_text="Create your save the date and share it today."),
    "text": dict(
        file="send-invitations-by-text.html", crumb="Send invitations by text",
        title="Send Free Digital Invitations by Text | MyInviteQR",
        desc="Send digital invitations by text message, WhatsApp or email with one link. Guests RSVP from their phone, no app needed. Free to design, pay once to publish.",
        keywords="send invitations by text, text message invitation, send invitation by WhatsApp, invitation link, how to send digital invitations, digital invitation by SMS, invitation via text, share invitation link",
        name="Text invitations", h1="Send digital invitations by text message in seconds",
        lead="Publish your invitation, copy the link and paste it into any text, WhatsApp or email. Guests tap once to open it and reply with one more tap.",
        why_title="Why text your invitation", why_sub="Fast, personal and impossible to miss.",
        why=[("send", "One link for everyone", "Paste your invitation link into any message app or group chat."), ("phone", "Opens on any phone", "No app to install. The invitation opens in the browser guests already use."), ("bell", "Follow up easily", "See who opened the invitation and who has not replied, then send a friendly nudge.")],
        steps_title="Send your invitation in four steps",
        tpl_title="Invitations made for phones", tpl_sub="Every template looks great on a small screen.", templates=["Boho Arch", "Balloon Bash", "Modern Hero", "Little Star"],
        wording_title="Text message wording ideas", wording_intro="Copy, paste and personalize.",
        wording=["You're invited to Sofia's birthday! Details and RSVP here: [link]", "We're getting married! Please see our invitation and RSVP by May 1: [link]", "Save the date! More details here: [link]"],
        split_title="Personal links for each guest", split_text="With Premium, send an individual link to each guest so their name is recognized when they open it and you see exactly who replied.",
        split_checks=["Works with iMessage, SMS, WhatsApp and email", "Individual links with Premium", "See who opened the invitation", "No app or account for guests"], split_alt="Digital invitation link shared in a text message",
        what_title="How do you send a digital invitation by text?",
        what=["Once your invitation is published, MyInviteQR gives you a link. Copy it and paste it into a text message, WhatsApp chat, email or social post. Guests tap the link and the invitation opens in their browser.",
              "Because the link always points to the latest version, you can correct details after sending without resending anything."],
        tips_title="Tips for texting invitations", tips=["Add a short personal note before the link.", "Send at a reasonable hour, not late at night.", "Use group chats for casual events and individual messages for formal ones.", "Include the reply-by date in your text.", "Send a reminder to guests who opened but did not reply."],
        faqs=[("Can I send a digital invitation by text message?", "Yes. Copy your invitation link and paste it into any text or chat app."),
              ("Will the link work on iPhone and Android?", "Yes. It opens in any modern browser."),
              ("Can I send it on WhatsApp?", "Yes. Paste the link into any WhatsApp chat or group."),
              ("Is texting acceptable for wedding invitations?", "For casual weddings, yes. Many couples text or email digital invitations and send printed cards to close family.")],
        cta_title="Send your first invitation", cta_text="Create it, copy the link and text it to your guests."),
}

MORE_POSTS = {
    "baby-shower-invitation-wording": dict(
        title="Free Baby Shower Invitation Wording Ideas | MyInviteQR",
        h1="Baby Shower Invitation Wording: 20 Free Ideas and Examples",
        desc="Free baby shower invitation wording ideas for every style: sweet, funny, co-ed and gender reveal. Copy an example and make it yours.",
        keywords="baby shower invitation wording, what to write on a baby shower invitation, baby shower invitation messages, funny baby shower invitation wording, co-ed baby shower invitation wording",
        date="2026-09-20", date_h="September 20, 2026", read=5,
        body="""<p>Baby shower invitation wording sets the tone for the party. Here are examples for every style and what to include.</p>
<h2>What to include</h2><ul><li>Name of the parent-to-be and host</li><li>Date, time and place</li><li>Registry or gift notes</li><li>Reply-by date and how to RSVP</li></ul>
<h2>Sweet and classic</h2><blockquote>Join us for a baby shower honoring Emma. Sunday, April 6 at 1:00 PM.</blockquote><blockquote>A little one is on the way! Come shower the mom-to-be with love.</blockquote>
<h2>Fun and modern</h2><blockquote>Diapers and wipes, oh my! Help us celebrate the newest addition.</blockquote><blockquote>Oh baby! Come eat, play and celebrate with us.</blockquote>
<h2>Co-ed showers</h2><blockquote>Two parents, one baby, lots of fun. Join us for a couples baby shower.</blockquote>
<h2>Gender reveal wording</h2><blockquote>He or she? Join us to find out!</blockquote>
<h2>Registry lines</h2><ul><li>Instead of a card, please bring a favorite children's book.</li><li>Your presence is the greatest gift. Registry details are on the invitation.</li></ul>
<p>With a digital invitation you can add the registry link, the address and a map in one place and update it any time.</p>"""),
    "birthday-invitation-wording": dict(
        title="Free Birthday Invitation Wording Ideas | MyInviteQR",
        h1="Birthday Invitation Wording: 25 Free Ideas for Kids and Adults",
        desc="Free birthday invitation wording for kids, teens and adults, from funny to formal. Copy a message and send it as a digital invitation.",
        keywords="birthday invitation wording, what to write on a birthday invitation, kids birthday invitation wording, funny birthday invitation wording, 30th birthday invitation wording",
        date="2026-09-20", date_h="September 20, 2026", read=5,
        body="""<p>Great birthday invitation wording is short, clear and fun. Use these free examples.</p>
<h2>Kids birthday wording</h2><blockquote>Sofia is turning 8! Join us for cake, games and lots of fun. Saturday, October 19 at 2:00 PM.</blockquote><blockquote>Let's party! Come celebrate with pizza, piñata and presents.</blockquote>
<h2>Teen birthday wording</h2><blockquote>Sweet 16 is here. Join us for a night of music and dancing.</blockquote>
<h2>Adult and milestone birthdays</h2><blockquote>Let's celebrate! Please join us for Daniel's 30th birthday dinner.</blockquote><blockquote>Fifty and fabulous. Dinner, drinks and dancing to celebrate 50 years.</blockquote>
<h2>Funny wording</h2><blockquote>Come help me get older with cake and a lot of laughs.</blockquote>
<h2>What to include</h2><ul><li>Guest of honor and age (optional)</li><li>Date, start and end time</li><li>Address, parking and dress code</li><li>How to RSVP and by when</li></ul>
<p>Send your invitation by text with a single link and see replies as they come in.</p>"""),
    "how-to-track-rsvps-for-your-event": dict(
        title="How to Track RSVPs for Your Event (Free Guide) | MyInviteQR",
        h1="How to Track RSVPs for Your Event: A Simple Free Guide",
        desc="Learn how to collect and track RSVPs online, send reminders and get an accurate headcount for weddings, parties and corporate events.",
        keywords="how to track RSVPs, RSVP tracker, collect RSVPs online, RSVP management, how to get guests to RSVP, RSVP reminder wording",
        date="2026-09-20", date_h="September 20, 2026", read=5,
        body="""<p>Tracking RSVPs can be stressful when replies arrive by text, email, phone and mail. Here is a simple system.</p>
<h2>1. Use one place for replies</h2><p>Add an RSVP button to your invitation so every answer lands in the same guest list.</p>
<h2>2. Ask for the details you need</h2><p>Ask for yes, no or maybe, the number of people in each party and any notes such as allergies.</p>
<h2>3. Set a reply-by date</h2><p>Pick a date that leaves time for final orders. For weddings, three to four weeks before the event is common.</p>
<h2>4. Follow up</h2><p>Filter your guest list by Pending and Not opened. Send a friendly reminder to those guests.</p>
<blockquote>Hi! Just checking in on our invitation. We would love to know if you can make it. Please reply by May 1.</blockquote>
<h2>5. Export your final list</h2><p>Download the guest list as CSV for your caterer, venue or seating chart.</p>"""),
    "quinceanera-invitation-ideas": dict(
        title="Free Quinceañera Invitation Ideas and Wording | MyInviteQR",
        h1="Quinceañera Invitation Ideas: Wording, Themes and Tips",
        desc="Free quinceañera invitation ideas, English and Spanish wording, color themes and tips for a beautiful digital invitation.",
        keywords="quinceanera invitation ideas, quinceanera invitation wording, quince invitation wording Spanish, sweet 15 invitation ideas, quinceañera themes",
        date="2026-09-20", date_h="September 20, 2026", read=5,
        body="""<p>A quinceañera invitation should feel as special as the celebration. Here are ideas for wording, colors and details.</p>
<h2>Wording in English</h2><blockquote>With the blessing of God and our parents, we invite you to celebrate the quincea&ntilde;era of Valentina.</blockquote>
<h2>Wording in Spanish</h2><blockquote>Con la bendici&oacute;n de Dios y de mis padres, te invito a celebrar mis quince a&ntilde;os.</blockquote>
<h2>Popular themes</h2><ul><li>Royal and regal in gold and navy</li><li>Enchanted garden with soft florals</li><li>Under the stars in midnight blue</li><li>Blush and rose gold</li></ul>
<h2>What to include</h2><ul><li>Ceremony time and church address</li><li>Reception time and venue</li><li>Dress code</li><li>RSVP and reply-by date</li></ul>
<p>A digital invitation lets you share both the ceremony and reception details in one place, in English and Spanish, and update them if plans change.</p>"""),
}
